services:
  postgres:
    image: postgres:18-alpine
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password 
      POSTGRES_DB: purch
    ports:
      - "5432:5432"
    volumes:
      - ./config/init.sql:/docker-entrypoint-initdb.d/init.sql
      # - postgres_data:/var/lib/postgresql/data 
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  purch:
    build: .
    container_name: service-purch
    secrets:
      - env
    ports:
      - "8080:8080"
    command: "./purch"
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped

volumes:
  postgres_data:
    
secrets:
  env:
    file: .env
