version: '3'

tasks:
  # ------- Docker commands -------
  build:
    cmds:
      - docker compose build
      
  # use a space delineated list 
  # of individual services to bring up 
  # if you don't want to bring everything up
  # e.g. task up -- postgres <-- only brings up the postgres container
  up:
    cmds:
      - docker compose -f docker-compose.yml up {{.CLI_ARGS}} -d

  # use a space delineated list 
  # of individual services to bring down
  # if you don't want to bring everything down
  # e.g. task down -- postgres <-- only brings down the postgres container
  down:
    cmds:
      - docker compose -f docker-compose.yml down {{.CLI_ARGS}}
      
  # ------- Lint -------
  lint:
    cmds:
      - golangci-lint run ./...

  format:
    cmds:
      - go fmt ./...
  
  vet:
    cmds:
      - go vet ./...

  nag:
    cmds:
      - task: format
      - task: vet

  # ------- Test ------- 
  test:
    aliases:
      - test-unit
    cmds:
      - ./test/test_endpoints.sh
