version: '3'

tasks:
  # ------- Docker commands -------
  build: ## Build the docker images
    cmds:
      - docker compose build
      
  # use a space delineated list 
  # of individual services to bring up 
  # if you don't want to bring everything up
  # e.g. task up -- postgres <-- only brings up the postgres container
  up: ## Spin up the docker containers
    cmds:
      - docker compose -f docker-compose.yml up {{.CLI_ARGS}} -d

  # use a space delineated list 
  # of individual services to bring down
  # if you don't want to bring everything down
  # e.g. task down -- postgres <-- only brings down the postgres container
  down: ## Bring down the docker containers
    cmds:
      - docker compose -f docker-compose.yml down {{.CLI_ARGS}}
      
  # ------- Lint -------
  lint: ## Run golangci-lint
    cmds:
      - golangci-lint run ./...

  format: ## Format the code
    cmds:
      - go fmt ./...
  
  vet: ## Vet the code
    cmds:
      - go vet ./...

  tidy: ## Run both format and vet
    cmds:
      - task: format
      - task: vet

  # ------- Test ------- 
  test: ## Run all the unit/integration tests
    cmds:
      - go test ./...
      
  # ------- Postgres -------
  psql:
    cmds:
      - psql postgres://postgres:password@localhost:5432/purch
