// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Account struct {
	ID     string
	ItemID string
	Name   string
}

type Category struct {
	ID                int64
	UserID            int64
	Label             string
	CurrentSpending   pgtype.Numeric
	AllocatedSpending pgtype.Numeric
}

type Item struct {
	ID                string
	UserID            int64
	AccessToken       string
	Name              string
	TransactionCursor string
}

type Transaction struct {
	ID             string
	AccountID      string
	CategoryID     string
	AuthorizedDate pgtype.Date
	SettledDate    pgtype.Date
	Merchant       pgtype.Text
	Amount         pgtype.Numeric
	CurrencyCode   pgtype.Text
	Pending        bool
}

type User struct {
	ID         int64
	FirstName  string
	LastName   string
	Username   string
	Password   string
	Income     pgtype.Numeric
	IncomeRate pgtype.Text
}
