// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteAccount = `-- name: DeleteAccount :exec
DELETE FROM accounts WHERE id = $1
`

func (q *Queries) DeleteAccount(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteAccount, id)
	return err
}

const deleteCategory = `-- name: DeleteCategory :exec
DELETE FROM categories WHERE id = $1
`

func (q *Queries) DeleteCategory(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteCategory, id)
	return err
}

const deleteItem = `-- name: DeleteItem :exec
DELETE FROM items WHERE id = $1
`

func (q *Queries) DeleteItem(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteItem, id)
	return err
}

const deleteTransaction = `-- name: DeleteTransaction :exec
DELETE FROM transactions WHERE id = $1
`

func (q *Queries) DeleteTransaction(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteTransaction, id)
	return err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users WHERE id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteUser, id)
	return err
}

const getAccount = `-- name: GetAccount :one

SELECT id, item_id, name FROM accounts
WHERE id = $1
`

// -------------------------
// Accounts related queries
// -------------------------
func (q *Queries) GetAccount(ctx context.Context, id string) (Account, error) {
	row := q.db.QueryRow(ctx, getAccount, id)
	var i Account
	err := row.Scan(&i.ID, &i.ItemID, &i.Name)
	return i, err
}

const getAccountTransactions = `-- name: GetAccountTransactions :one
SELECT t.id, t.account_id, t.category_id, t.authorized_date, t.settled_date, t.merchant, t.amount, t.currency_code, t.pending
FROM transactions t
JOIN accounts a ON t.account_id = a.id
`

func (q *Queries) GetAccountTransactions(ctx context.Context) (Transaction, error) {
	row := q.db.QueryRow(ctx, getAccountTransactions)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.CategoryID,
		&i.AuthorizedDate,
		&i.SettledDate,
		&i.Merchant,
		&i.Amount,
		&i.CurrencyCode,
		&i.Pending,
	)
	return i, err
}

const getCategory = `-- name: GetCategory :one

SELECT id, user_id, label, current_spending, allocated_spending FROM categories
WHERE id = $1 LIMIT 1
`

// ---------------------------
// Categories related queries
// ---------------------------
func (q *Queries) GetCategory(ctx context.Context, id int64) (Category, error) {
	row := q.db.QueryRow(ctx, getCategory, id)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Label,
		&i.CurrentSpending,
		&i.AllocatedSpending,
	)
	return i, err
}

const getItem = `-- name: GetItem :one

SELECT id, user_id, access_token, name, transaction_cursor FROM items
WHERE id = $1
`

// ---------------------
// Items related queries
// ---------------------
func (q *Queries) GetItem(ctx context.Context, id string) (Item, error) {
	row := q.db.QueryRow(ctx, getItem, id)
	var i Item
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AccessToken,
		&i.Name,
		&i.TransactionCursor,
	)
	return i, err
}

const getItemAccounts = `-- name: GetItemAccounts :many
SELECT id, item_id, name FROM accounts
WHERE item_id = $1
`

func (q *Queries) GetItemAccounts(ctx context.Context, itemID string) ([]Account, error) {
	rows, err := q.db.Query(ctx, getItemAccounts, itemID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Account
	for rows.Next() {
		var i Account
		if err := rows.Scan(&i.ID, &i.ItemID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTransaction = `-- name: GetTransaction :one

SELECT id, account_id, category_id, authorized_date, settled_date, merchant, amount, currency_code, pending FROM transactions
WHERE id = $1
`

// -----------------------------
// Transactions related queries
// -----------------------------
func (q *Queries) GetTransaction(ctx context.Context, id string) (Transaction, error) {
	row := q.db.QueryRow(ctx, getTransaction, id)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.CategoryID,
		&i.AuthorizedDate,
		&i.SettledDate,
		&i.Merchant,
		&i.Amount,
		&i.CurrencyCode,
		&i.Pending,
	)
	return i, err
}

const getUserAccounts = `-- name: GetUserAccounts :many
SELECT a.id, a.item_id, a.name
FROM items i
JOIN accounts a ON i.id = a.item_id
WHERE i.user_id = $1
`

func (q *Queries) GetUserAccounts(ctx context.Context, userID int64) ([]Account, error) {
	rows, err := q.db.Query(ctx, getUserAccounts, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Account
	for rows.Next() {
		var i Account
		if err := rows.Scan(&i.ID, &i.ItemID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserById = `-- name: GetUserById :one

SELECT id, first_name, last_name, username, password, income, income_rate FROM users
WHERE id = $1 LIMIT 1
`

// ---------------------
// User related queries
// ---------------------
func (q *Queries) GetUserById(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRow(ctx, getUserById, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.LastName,
		&i.Username,
		&i.Password,
		&i.Income,
		&i.IncomeRate,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, first_name, last_name, username, password, income, income_rate FROM users
WHERE username = $1 LIMIT 1
`

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByUsername, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.LastName,
		&i.Username,
		&i.Password,
		&i.Income,
		&i.IncomeRate,
	)
	return i, err
}

const getUserCategories = `-- name: GetUserCategories :many
SELECT id, user_id, label, current_spending, allocated_spending FROM categories
WHERE user_id = $1
`

func (q *Queries) GetUserCategories(ctx context.Context, userID int64) ([]Category, error) {
	rows, err := q.db.Query(ctx, getUserCategories, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Category
	for rows.Next() {
		var i Category
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Label,
			&i.CurrentSpending,
			&i.AllocatedSpending,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserItems = `-- name: GetUserItems :many
SELECT id, user_id, access_token, name, transaction_cursor FROM items
WHERE user_id = $1
`

func (q *Queries) GetUserItems(ctx context.Context, userID int64) ([]Item, error) {
	rows, err := q.db.Query(ctx, getUserItems, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Item
	for rows.Next() {
		var i Item
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.AccessToken,
			&i.Name,
			&i.TransactionCursor,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserTransactions = `-- name: GetUserTransactions :many
SELECT t.id, t.account_id, t.category_id, t.authorized_date, t.settled_date, t.merchant, t.amount, t.currency_code, t.pending
FROM items i
JOIN accounts a ON i.id = a.item_id
JOIN transactions t ON a.id = t.account_id
WHERE i.user_id = $1
`

func (q *Queries) GetUserTransactions(ctx context.Context, userID int64) ([]Transaction, error) {
	rows, err := q.db.Query(ctx, getUserTransactions, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Transaction
	for rows.Next() {
		var i Transaction
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.CategoryID,
			&i.AuthorizedDate,
			&i.SettledDate,
			&i.Merchant,
			&i.Amount,
			&i.CurrencyCode,
			&i.Pending,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const storeAccount = `-- name: StoreAccount :one
INSERT INTO accounts (
    item_id,
    name
) VALUES (
    $1, $2
)
RETURNING id, item_id, name
`

type StoreAccountParams struct {
	ID     string
	ItemID string
	Name   string
}

func (q *Queries) StoreAccount(ctx context.Context, arg StoreAccountParams) (Account, error) {
	row := q.db.QueryRow(ctx, storeAccount, arg.ID, arg.ItemID, arg.Name)
	var i Account
	err := row.Scan(&i.ID, &i.ItemID, &i.Name)
	return i, err
}

const storeCategory = `-- name: StoreCategory :one
INSERT INTO categories (
    user_id,
    label,
    allocated_spending
) VALUES (
    $1, $2, $3
)
RETURNING id, user_id, label, current_spending, allocated_spending
`

type StoreCategoryParams struct {
	UserID            int64
	Label             string
	AllocatedSpending pgtype.Numeric
}

func (q *Queries) StoreCategory(ctx context.Context, arg StoreCategoryParams) (Category, error) {
	row := q.db.QueryRow(ctx, storeCategory, arg.UserID, arg.Label, arg.AllocatedSpending)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Label,
		&i.CurrentSpending,
		&i.AllocatedSpending,
	)
	return i, err
}

const storeItem = `-- name: StoreItem :one
INSERT INTO items (
    id,
    user_id,
    access_token,
    name
) VALUES (
    $1, $2, $3, $4
)
RETURNING id, user_id, access_token, name, transaction_cursor
`

type StoreItemParams struct {
	ID              string
	UserID          int64
	AccessToken     string
	Name        string
}

func (q *Queries) StoreItem(ctx context.Context, arg StoreItemParams) (Item, error) {
	row := q.db.QueryRow(ctx, storeItem, arg.ID, arg.UserID, arg.AccessToken, arg.Name)
	var i Item
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AccessToken,
		&i.Name,
		&i.TransactionCursor,
	)
	return i, err
}

const storeTransaction = `-- name: StoreTransaction :one
INSERT INTO transactions (
    id,
    account_id,
    category_id,
    authorized_date,
    merchant,
    amount,
    currency_code,
    pending
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8
)
RETURNING id, account_id, category_id, authorized_date, settled_date, merchant, amount, currency_code, pending
`

type StoreTransactionParams struct {
	ID             string
	AccountID      string
	CategoryID     string
	AuthorizedDate pgtype.Date
	Merchant       pgtype.Text
	Amount         pgtype.Numeric
	CurrencyCode   pgtype.Text
	Pending        bool
}

func (q *Queries) StoreTransaction(ctx context.Context, arg StoreTransactionParams) (Transaction, error) {
	row := q.db.QueryRow(ctx, storeTransaction,
		arg.ID,
		arg.AccountID,
		arg.CategoryID,
		arg.AuthorizedDate,
		arg.Merchant,
		arg.Amount,
		arg.CurrencyCode,
		arg.Pending,
	)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.CategoryID,
		&i.AuthorizedDate,
		&i.SettledDate,
		&i.Merchant,
		&i.Amount,
		&i.CurrencyCode,
		&i.Pending,
	)
	return i, err
}

const storeUser = `-- name: StoreUser :one
INSERT INTO users (
    first_name, 
    last_name,
    username,
    password,
    income,
    income_rate
) VALUES (
    $1, $2, $3, $4, $5, $6
)
RETURNING id, first_name, last_name, username, password, income, income_rate
`

type StoreUserParams struct {
	FirstName  string         `form:"first_name"  json:"first_name"`
	LastName   string         `form:"last_name"   json:"last_name"`
	Username   string         `form:"username"    json:"username"`
	Password   string         `form:"password"    json:"password"`
	Income     pgtype.Numeric `form:"income"      json:"income"`
	IncomeRate pgtype.Text    `form:"income_rate" json:"income_rate"`
}

func (q *Queries) StoreUser(ctx context.Context, arg StoreUserParams) (User, error) {
	row := q.db.QueryRow(ctx, storeUser,
		arg.FirstName,
		arg.LastName,
		arg.Username,
		arg.Password,
		arg.Income,
		arg.IncomeRate,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.LastName,
		&i.Username,
		&i.Password,
		&i.Income,
		&i.IncomeRate,
	)
	return i, err
}

const updateAccount = `-- name: UpdateAccount :one
UPDATE accounts
    set name = $2
WHERE id = $1
RETURNING id, item_id, name
`

type UpdateAccountParams struct {
	ID   string
	Name string
}

func (q *Queries) UpdateAccount(ctx context.Context, arg UpdateAccountParams) (Account, error) {
	row := q.db.QueryRow(ctx, updateAccount, arg.ID, arg.Name)
	var i Account
	err := row.Scan(&i.ID, &i.ItemID, &i.Name)
	return i, err
}

const updateCategory = `-- name: UpdateCategory :one
UPDATE categories
    set current_spending = $2,
    allocated_spending = $3
WHERE id = $1
RETURNING id, user_id, label, current_spending, allocated_spending
`

type UpdateCategoryParams struct {
	ID                int64
	CurrentSpending   pgtype.Numeric
	AllocatedSpending pgtype.Numeric
}

func (q *Queries) UpdateCategory(ctx context.Context, arg UpdateCategoryParams) (Category, error) {
	row := q.db.QueryRow(ctx, updateCategory, arg.ID, arg.CurrentSpending, arg.AllocatedSpending)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Label,
		&i.CurrentSpending,
		&i.AllocatedSpending,
	)
	return i, err
}

const updateItem = `-- name: UpdateItem :one
UPDATE items
    set name = $2,
    transaction_cursor = $3
WHERE id = $1
RETURNING id, user_id, access_token, name, transaction_cursor
`

type UpdateItemParams struct {
	ID                string
	Name              string
	TransactionCursor string
}

func (q *Queries) UpdateItem(ctx context.Context, arg UpdateItemParams) (Item, error) {
	row := q.db.QueryRow(ctx, updateItem, arg.ID, arg.Name, arg.TransactionCursor)
	var i Item
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AccessToken,
		&i.Name,
		&i.TransactionCursor,
	)
	return i, err
}

const updateTransaction = `-- name: UpdateTransaction :one
UPDATE transactions
    set settled_date = $2,
    amount = $3,
    pending = $4
WHERE id = $1
RETURNING id, account_id, category_id, authorized_date, settled_date, merchant, amount, currency_code, pending
`

type UpdateTransactionParams struct {
	ID          string
	SettledDate pgtype.Date
	Amount      pgtype.Numeric
	Pending     bool
}

func (q *Queries) UpdateTransaction(ctx context.Context, arg UpdateTransactionParams) (Transaction, error) {
	row := q.db.QueryRow(ctx, updateTransaction,
		arg.ID,
		arg.SettledDate,
		arg.Amount,
		arg.Pending,
	)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.CategoryID,
		&i.AuthorizedDate,
		&i.SettledDate,
		&i.Merchant,
		&i.Amount,
		&i.CurrencyCode,
		&i.Pending,
	)
	return i, err
}

const updateUser = `-- name: UpdateUser :one
UPDATE users
    set first_name = $2,
    last_name = $3,
    username = $4,
    password = $5,
    income = $6,
    income_rate = $7
WHERE id = $1
RETURNING id, first_name, last_name, username, password, income, income_rate
`

type UpdateUserParams struct {
	ID         int64
	FirstName  string
	LastName   string
	Username   string
	Password   string
	Income     pgtype.Numeric
	IncomeRate pgtype.Text
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUser,
		arg.ID,
		arg.FirstName,
		arg.LastName,
		arg.Username,
		arg.Password,
		arg.Income,
		arg.IncomeRate,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.LastName,
		&i.Username,
		&i.Password,
		&i.Income,
		&i.IncomeRate,
	)
	return i, err
}
