definitions:
  database.User:
    properties:
      first_name:
        type: string
      id:
        type: string
      income:
        type: number
      income_rate:
        type: string
      last_name:
        type: string
      password:
        type: string
      username:
        type: string
    type: object
info:
  contact: {}
paths:
  /api/user/delete:
    get:
      consumes:
      - application/json
      description: do deleteUser
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: deleteUser example
      tags:
      - user
  /api/user/exchange-public-token:
    get:
      consumes:
      - application/json
      description: do exchangePublicToken
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: exchangePublicToken example
      tags:
      - user
  /api/user/info:
    get:
      consumes:
      - application/json
      description: do getUserInfo
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: getUserInfo example
      tags:
      - user
  /api/user/link-token:
    get:
      consumes:
      - application/json
      description: do getLinkToken
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: getLinkToken example
      tags:
      - user
  /api/user/login:
    get:
      consumes:
      - application/json
      description: do setUserCookie
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: setUserCookie example
      tags:
      - user
  /api/user/logout:
    get:
      consumes:
      - application/json
      description: do logout
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: logout example
      tags:
      - user
  /api/user/register:
    post:
      consumes:
      - application/json
      description: do resgisterUser
      parameters:
      - description: User Registration Info
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/database.User'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: resgisterUser example
      tags:
      - user
  /api/user/update:
    get:
      consumes:
      - application/json
      description: do updateUser
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: updateUser example
      tags:
      - user
swagger: "2.0"
